#!/usr/bin/env bash
set -Ceu

TOOLS=(
  "git"
  "vim"
  "make"
  "curl"
)

# Prerequites checking
for cmd in "${TOOLS[@]}"; do
  if ! type $cmd &> /dev/null; then
    echo "$cmd is required to be installed."
    exit 1
  fi
done

# Install dotfiles
ln -snvf "$(pwd)/_vimrc" "$HOME/_vimrc"
ln -snvf "$(pwd)/_screenrc" "$HOME/.screenrc"
ln -snvf "$(pwd)/_bashrc" "$HOME/.bashrc"
ln -snvf "$(pwd)/_bash_profile" "$HOME/.bash_profile"
ln -snvf "$(pwd)/etc/_gitconfig" "$HOME/.gitconfig"
ln -snvf "$(pwd)/etc/_gitconfig_global" "$HOME/.gitignore_global"
ln -snvf "$(pwd)/etc/_hyper.js" "$HOME/.hyper.js"
ln -svnf "$(pwd)/etc/_pryrc" "$HOME/.pryrc"

# Install _vimrc
if [ ! -e "$HOME/.vim" ] ; then
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  (set -x; vim +PlugInstall +qall)
fi

# Loads .bashrc
clear
(set -x; exec $SHELL --login)
