#!/usr/bin/env bash
set -Ceu

# Install dotfiles
ln -snvf "$(pwd)/_vimrc" "$HOME/_vimrc"
ln -snvf "$(pwd)/_screenrc" "$HOME/.screenrc"
ln -snvf "$(pwd)/_bashrc" "$HOME/.bashrc"
ln -snvf "$(pwd)/_bash_profile" "$HOME/.bash_profile"
ln -snvf "$(pwd)/etc/_gitconfig" "$HOME/.gitconfig"
ln -snvf "$(pwd)/etc/_gitconfig_global" "$HOME/.gitignore_global"
ln -snvf "$(pwd)/etc/_hyper.js" "$HOME/.hyper.js"
ln -svnf "$(pwd)/etc/_pryrc" "$HOME/.pryrc"

# Install _vimrc
if [ ! -e "$HOME/.vim" ] ; then
  if type curl &> /dev/null ; then
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    (set -x; vim +PlugInstall +qall)
  else
    echo "Git not available." && exit 1
  fi
fi

# Install nvm and rbenv
if [ $# -eq 1 ] && [ $1 == "--skip-scripts" ] ; then
  echo "Scripts installation skipped."
else
  [ ! -e "$HOME/.nvm" ] && ./scripts/nvm.sh
  [ ! -e "$HOME/.rbenv" ] && ./scripts/rbenv.sh
fi

# Loads .bashrc
clear
(set -x; exec $SHELL --login)
