#!/bin/bash
set -Ceu

# Install dotfiles
ln -snvf "$(pwd)/_vimrc" "$HOME/_vimrc"
ln -snvf "$(pwd)/_screenrc" "$HOME/.screenrc"
ln -snvf "$(pwd)/_bashrc" "$HOME/.bashrc"
ln -snvf "$(pwd)/_bash_profile" "$HOME/.bash_profile"
ln -snvf "$(pwd)/etc/_gitconfig" "$HOME/.gitconfig"
ln -snvf "$(pwd)/etc/_gitconfig_global" "$HOME/.gitignore_global"
ln -snvf "$(pwd)/etc/_hyper.js" "$HOME/.hyper.js"
ln -svnf "$(pwd)/etc/_pryrc" "$HOME/.pryrc"

# Install _vimrc
if [ ! -e "$HOME/.vim/bundle" ] ; then
  if type git &> /dev/null ; then
    git clone https://github.com/VundleVim/Vundle.vim.git "$HOME/.vim/bundle/Vundle.vim"
  else
    echo "Git not available" && exit 1
  fi
fi

(set -x; vim +PluginInstall +qall)
(cd "$HOME/.vim/bundle/vimproc/"; make)

# Install nvm and rbenv
[ ! -e "$HOME/.nvm" ] && ./scripts/nvm.sh
[ ! -e "$HOME/.rbenv" ] && ./scripts/rbenv.sh

# Loads .bashrc
clear
(set -x; exec $SHELL --login)
