#!/bin/bash
set -Ceux

unlink "$HOME/_vimrc"
unlink "$HOME/.screenrc"
unlink "$HOME/.bashrc"
unlink "$HOME/.bash_profile"
unlink "$HOME/.starship.toml"
unlink "$HOME/.gitconfig"
unlink "$HOME/.gitignore_global"
unlink "$HOME/.hyper.js"

rm -rf "$HOME/.vim"

(set +x; clear)
exec bash --login

set +x
