#!/bin/bash
set -Ceux

unlink "$HOME/_vimrc"
unlink "$HOME/.screenrc"
unlink "$HOME/.bashrc"
unlink "$HOME/.bash_profile"
unlink "$HOME/.starship.toml"
unlink "$HOME/.alacritty.yml"
unlink "$HOME/.gitconfig"
unlink "$HOME/.gitignore_global"
unlink "$HOME/.hyper.js"
unlink "$HOME/.pryrc"

sudo unlink "/usr/local/bin/gctool"

exec bash --login
