#!/bin/bash
set -Ceux

unlink "$HOME/.pi/agent/settings.json"
unlink "$HOME/.vimrc"
unlink "$HOME/.tmux.conf"
unlink "$HOME/.bashrc"
unlink "$HOME/.starship.toml"
unlink "$HOME/.alacritty.toml"
unlink "$HOME/.config/herdr/config.toml"
unlink "$HOME/.gitconfig"
unlink "$HOME/.gitignore_global"
unlink "$HOME/.tigrc"

exec bash --login
